### ISSUE TITLE
Minor correction

### ISSUE THREAD

**Issue by JasonDonFreeman** [Kylep342/538_Riddler#1]
Hi Kyle,

This is great but I think your last point"…has 2,652,345,952,577,569 (about 2.65 quadrillion) digits. If you were to write one digit of that number every second, a decade wouldn’t quite cut it" is a bit of an understatement. It would take over 84 million years!

Other than that, this is very nicely done. 

Regards,
Jason Freeman

**Comment by Kylep342** [comment]
Hi Jason,

I am aware it is an understatement; it was meant to be so. I was trying to come up with a clever way to end my writeup in hopes of getting noticed by Zach at fivethirtyeight.

I worked out the time it would actually, and thought about noting that "you'd have to start when the dinosaurs were alive and kicking", but figured circling back to the [phrasing in the original question](https://fivethirtyeight.com/features/how-many-ways-can-you-raid-the-candy-shop/l) would do the trick of getting noticed.

I appreciate the feedback!

Best,
Kyle
